### ISSUE TITLE
Image distortion -L-R jpg format

### ISSUE THREAD

**Issue by snblg** [steren/stereo-img#44]
Left-right photos are anamorphic at the top and bottom of the screen. 
Whatever the format !
Tested on Quest 3.

You can compare your pictures with stereo photo maker results 
(Make html5 stereo viewer option)

I cannot use your component !

**Comment by steren** [comment]
Would you have a file example?

**Comment by snblg** [comment]
Yes, I did send it in response to your email.
Do you use a sphere or a plan for left right pictures ?
A sphere would explain the problem I see !
Or,
the aspect ratio is bad.

**Comment by steren** [comment]
This issue has been fixed, see https://github.com/steren/stereo-img/issues/37

For non 180 angle, the component now uses a flat rectangle, not a sphere. 

Please upgrade to the latest version

**Comment by snblg** [comment]
Distortion still there using your flat rectangle !
See my lest private message and sample jpg file.

**Comment by steren** [comment]
Please attach the image to this issue and please try to get a screenshot when loading it in the viewer.

**Comment by snblg** [comment]
I did send you a private message using your email address.
You will be able to see your component on my website, 
you will be able to compare and understand the distortion problem.

**Comment by snblg** [comment]
**Closed but not solved.**
I did download your latest component in case you changed something.
But display problem is still here !

I will use Stereo photo maker to view my online left right pictures
It's screen is not flat, but stereo is OK with all L/R pictures & oculus Quest (2 or 3)
I just need some tuning (entering full screen & vr automatically)
